// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBB7SU_XxUjniRx0jF5flld2mrWyptMrW4',
    appId: '1:689618440082:web:51632b07c75047de7dfb4b',
    messagingSenderId: '689618440082',
    projectId: 'serveasy-b3b33',
    authDomain: 'serveasy-b3b33.firebaseapp.com',
    storageBucket: 'serveasy-b3b33.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXVYka-lPLVId_8kiRy9vxhV0pVOy7SdQ',
    appId: '1:689618440082:android:44a896a456ce93c67dfb4b',
    messagingSenderId: '689618440082',
    projectId: 'serveasy-b3b33',
    storageBucket: 'serveasy-b3b33.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoAF0DtVDYHx_HbDn7T-Xv_5EWuhaTcDs',
    appId: '1:689618440082:ios:bab784cd95b460f47dfb4b',
    messagingSenderId: '689618440082',
    projectId: 'serveasy-b3b33',
    storageBucket: 'serveasy-b3b33.appspot.com',
    iosClientId: '689618440082-5fajtgvul3o0fqj1kdsnk4uudq6vc5u2.apps.googleusercontent.com',
    iosBundleId: 'com.example.project2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoAF0DtVDYHx_HbDn7T-Xv_5EWuhaTcDs',
    appId: '1:689618440082:ios:b1e8e3f4a6bc74c27dfb4b',
    messagingSenderId: '689618440082',
    projectId: 'serveasy-b3b33',
    storageBucket: 'serveasy-b3b33.appspot.com',
    iosClientId: '689618440082-aopaa335fal7u72tk1btl7a3fvaauppl.apps.googleusercontent.com',
    iosBundleId: 'com.example.project2.RunnerTests',
  );
}
